### ISSUE TITLE
Player opens details screen on list scroll on Android 2.2+

### ISSUE THREAD

**Issue by marisks** [chrissie1/HanselMinutesPlayer#1]
When I scroll list of episodes, it always opens details screen of last selected episode. It happens on my HTC Desire with Android 2.3.

P.S. Thanks for great player :)

**Comment by chrissie1** [comment]
There should be new version that fixes this.

Christiaan Baes
twitter: chrissie1 http://twitter.com/#%21/chrissie1
Blog http://blogs.lessthandot.com/index.php/All/?disp=authdir&author=7
co-founder of Lessthandot http://lessthandot.com

Op 1/02/2012 6:19, marisks schreef:

**Comment by chrissie1** [comment]
Fixed in version 1.3.1

**Comment by marisks** [comment]
It works now fine. Thanks!
